### ISSUE TITLE
Organize README docs for apps and root folder

### ISSUE THREAD

**Issue by nesterone** [Mentorioum/mentorioum-platform#10]
- [x] Provide installation and run the app instructions
- [x] Add doc for `github-sync` with images for workflows

**Comment by 0pdd** [comment]
@nesterone the puzzle [#15](https://github.com/Mentorioum/mentorioum-platform/issues/15) is still not solved.

**Comment by 0pdd** [comment]
@nesterone 2 puzzles [#17](https://github.com/Mentorioum/mentorioum-platform/issues/17), [#18](https://github.com/Mentorioum/mentorioum-platform/issues/18) are still not solved; solved: [#15](https://github.com/Mentorioum/mentorioum-platform/issues/15).
